### ISSUE TITLE
Change license to GPL

### ISSUE THREAD

**Issue by brylie** [creativecommons/wp-plugin-cc-gutenberg-blocks#5]
This project is currently MIT licensed. However, Gutenberg is GPL licensed and so [the "share alike" aspect of GPL should apply to all Gutenberg blocks projects](https://github.com/WordPress/gutenberg/issues/5281#issuecomment-368754372).

## Task

- [ ] Change the license for this project to "GPL v3 or later"

**Comment by brylie** [comment]
@hugosolar, since you are the sole contributor to this project, would you approve our relicensing the code from MIT to GPL?

**Comment by hugosolar** [comment]
I agree, It makes perfect sense to me due to https://github.com/WordPress/gutenberg/issues/5281  👍

**Comment by brylie** [comment]
Done. Thanks!
